---
title: "gravity_model"
author: "Brecht Nijman"
date: "6/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Data & Packages



```{r libraries}
library(tidyverse)
library(glmnet)
# library(readr)
library(magrittr)
library(ggplot2)
library(firatheme)
library(stargazer)

```

```{r}
# knitr::root.dir("")
```

```{r}
getwd()
```


```{r load edges}
setwd("/Users/brecht/Documents/citynet_2")
edges <- read_delim("citynet/src/output/edges.csv",
                         ";", escape_double = FALSE, 
                         col_types = 
                           cols(border_DUM = col_factor(levels = c("0", "1")), 
                                FR_con = col_factor(levels = c("0", "1")), 
                                FR_int = col_factor(levels = c("0", "1")), 
                                EN_con = col_factor(levels = c("0", "1")), 
                                EN_int = col_factor(levels = c("0", "1"))), 
                         trim_ws = TRUE)

edges <- tibble(edges)
head(edges)
```


```{r}
setwd("/Users/brecht/Documents/citynet_2")
nodes <- read_delim("citynet/src/output/nodes.csv",
                         ";", escape_double = FALSE, 
                         col_types = 
                           cols(FR_DUM = col_factor(levels = c("0", "1")), 
                                EN_DUM = col_factor(levels = c("0", "1"))), 
                         trim_ws = TRUE)

nodes <- tibble(nodes)
#nodes <- select(nodes, -c(X1))
head(nodes)
```

## Nodes
```{r create variable FR_EN}
nodes <- mutate(nodes,
       lang = ifelse(EN_DUM == 1, "EN", ifelse(FR_DUM == 1, "FR", "OTHER")))
```

```{r}
nodes
```
```{r}
ggplot(nodes, aes(x=log(en_deg_prop), y=log(fr_deg_prop))) +
  geom_abline(slope = 1, intercept = 0, alpha = .5) +
  geom_point(aes(fill=REGION, size=POP), shape = 21) +
  # scale_shape_manual(values = c(21, 22, 23), labels=c('English', 'French', 'Other')) +
  scale_fill_brewer(palette = "Set2", labels=c('central east', 'north', 'south', 'west'))+
  xlim(-5, 3.5) +
  ylim(-5, 3.5) +
  xlab("Proportional degree centrality in the English network (ln)")+
  ylab("Proportional degree centrality in the French network (ln)")+
  labs(fill="Region", size="Pop (x 1000)") +
  theme_classic() +
  # theme(legend.position = c(.9, .2)) +
  theme(text = element_text(size = 9)) + 
  theme(panel.grid.major = element_line(linetype = 'dashed', colour = "grey50", size = .05),
        panel.grid.minor = element_line(linetype = 'dashed', colour = "grey50", size = .05),
        legend.background = element_blank(),
        legend.box.background = element_rect(colour = "black"))


```

```{r}
degree_cor2 <-
  ggplot(nodes, aes(x=log(en_deg_prop), y=log(fr_deg_prop), shape=lang)) +
  geom_abline(slope = 1, intercept = 0, alpha = .5) +
  geom_point(aes(fill=lang), size = 2.5) +
  xlim(-5, 3.5) +
  ylim(-5, 3.5) +
  xlab("Proportional degree centrality in the English network (ln)")+
  ylab("Proportional degree centrality in the French network (ln)")+
  scale_fill_brewer(palette = "Set2", labels=c('English', 'French', 'Other'))+
  scale_shape_manual(values = c(21, 22, 23), labels=c('English', 'French', 'Other')) +
  labs(fill="Language Sphere", shape="Language Sphere") +
  theme_classic() +
  # theme(text = element_text(family='serif', size = 9)) +
  theme(text = element_text(size = 9)) +
  theme(legend.position = c(.9, .2)) +
  theme(panel.grid.major = element_line(linetype = 'dashed', colour = "grey50", size = .05),
        panel.grid.minor = element_line(linetype = 'dashed', colour = "grey50", size = .05),
        legend.background = element_blank(),
        legend.box.background = element_rect(colour = "black"))

degree_cor2
```


```{r}
# ggsave("degreefigure.png", height = 4, width = 5)
```


## Edges

```{r}
head(edges)
```

```{r}
# edges <- mutate(edges,
#        lang = ifelse(EN_con == 1, "EN", ifelse(FR_con == 1, "FR", "OTHER")))

edges <- mutate(edges,
       lang = ifelse((EN_con == 1 & FR_con == 0), "EN", ifelse((EN_con == 0 & FR_con == 1) , "FR", ifelse((EN_con == 1 & FR_con == 1), "BOTH", "OTHER"))))

edges <- mutate(edges,
       lang_int = ifelse(EN_int == 1, "EN", ifelse(FR_int == 1, "FR", "OTHER")))
```

```{r}
# subset without 0s
edges_nz <- subset(edges, col_en > 0)
edges_nz <- subset(edges_nz, col_fr > 0)

```

```{r}
# cooc_scatter <-
#   ggplot(edges_nz, aes(log(col_prop_en), log(col_prop_fr), fill=lang, shape=lang)) +
#   geom_point(size = 2.5) +
#   xlim(-10, 1) +
#   ylim(-10, 1) +
#   geom_abline(alpha = .5) +
#   scale_fill_brewer(palette = "BrBG", labels=c('Both','English', 'French', 'Other')) +
#   scale_shape_manual(values = c(21, 22, 23, 24), labels=c('Both','English', 'French', 'Other')) +
#   # scale_shape(labels=c('Both','English', 'French', 'Other')) +
#   labs(fill="Language Sphere", shape="Language Sphere") +
#   xlab("Proportional city-pair co-occurence in the English network (log)")+
#   ylab("Proportional city-pair co-occurence in the French network (log)") +
#   theme_classic() +
#   # theme(text = element_text(family = 'serif', size = 9)) +
#   theme(legend.position = c(.9, .2)) +
#   theme(panel.grid.major = element_line(linetype = 'dashed', colour = "grey50", size = .05),
#         panel.grid.minor = element_line(linetype = 'dashed', colour = "grey50", size = .05),
#         legend.background = element_blank(),
#         legend.box.background = element_rect(colour = "black"))
# 
# cooc_scatter
```


```{r}
cooc_scatter2 <-
  ggplot(edges_nz, aes(log(col_prop_en), log(col_prop_fr), fill=lang_int, shape=lang_int)) +
  geom_point(size = 2.5) +
  xlim(-10, 1) +
  ylim(-10, 1) +
  geom_abline(alpha = .5) +
  scale_fill_brewer(palette = "Set2", labels=c('English', 'French', 'Other')) +
  scale_shape_manual(values = c(21, 22, 23), labels=c('English', 'French', 'Other')) +
  # scale_shape(labels=c('Both','English', 'French', 'Other')) +
  labs(fill="Language Sphere", shape="Language Sphere") +
  xlab("Proportional city-pair co-occurence in the English network (ln)")+
  ylab("Proportional city-pair co-occurence in the French network (ln)") +
  theme_classic() +
  # theme(text = element_text(family = 'serif', size = 9)) +
  theme(text = element_text(size = 9)) +
  theme(legend.position = c(.9, .2)) +
  theme(panel.grid.major = element_line(linetype = 'dashed', colour = "grey50", size = .05),
        panel.grid.minor = element_line(linetype = 'dashed', colour = "grey50", size = .05),
        legend.background = element_blank(),
        legend.box.background = element_rect(colour = "black"))

cooc_scatter2
```

```{r}
# ggsave("coocfigure.png", height = 4, width = 5)
```

## Gravity Model

```{r}
# # subset without 0s
# edges_nz_en <- subset(edges, col_en > 0)
# edges_nz_fr <- subset(edges, col_fr > 0)

# subset only cities with population of over a million
edges_mil <-
  edges_nz %>% 
  filter(POP_A > 999 & POP_B > 999)

head(edges_mil)
```

### French

```{r}
# base model french
lm.fr1 <- lm(log(col_fr) ~ log(POP_A) + log(POP_B) + log(distance), edges_nz)
summary(lm.fr1)
```

```{r}
# fr model with border
lm.fr2 <- lm(log(col_fr) ~ log(POP_A) + log(POP_B) + log(distance) + border_DUM, edges_nz)
summary(lm.fr2)
```

```{r}

# fr model with border + language sphere only french
lm.fr3 <- lm(log(col_fr) ~ log(POP_A) + log(POP_B) + log(distance) + border_DUM + FR_con, edges_nz)
summary(lm.fr3)

```


```{r}

# fr model with border + language sphere only french
lm.fr4 <- lm(log(col_fr) ~ log(POP_A) + log(POP_B) + log(distance) + border_DUM + FR_con + EN_con, edges_nz)
summary(lm.fr4)

```

```{r}
# fr model 1 mil base
lm.fr5 <- lm(log(col_fr) ~ log(POP_A) + log(POP_B) + log(distance), edges_mil)
summary(lm.fr5)
```

```{r}
# fr model 1 mil full
lm.fr6 <- lm(log(col_fr) ~ log(POP_A) + log(POP_B) + log(distance) + border_DUM + FR_con + EN_con, edges_nz)
summary(lm.fr6)
```


### English

```{r}
# base model english
lm.en1 <- lm(log(col_en) ~ log(POP_A) + log(POP_B) + log(distance), edges_nz)
summary(lm.en1)
```

```{r}
# en model with border
lm.en2 <- lm(log(col_en) ~ log(POP_A) + log(POP_B) + log(distance) + border_DUM, edges_nz)
summary(lm.en2)
```

```{r}

# fr model with border + language sphere only french
lm.en3 <- lm(log(col_en) ~ log(POP_A) + log(POP_B) + log(distance) + border_DUM + EN_con, edges_nz)
summary(lm.en3)

```


```{r}

# fr model with border + language sphere only french
lm.en4 <- lm(log(col_en) ~ log(POP_A) + log(POP_B) + log(distance) + border_DUM + FR_con + EN_con, edges_nz)
summary(lm.en4)

```


```{r}
# en model 1 mil base
lm.en5 <- lm(log(col_en) ~ log(POP_A) + log(POP_B) + log(distance), edges_mil)
summary(lm.en5)
```

```{r}
# en model 1 mil full
lm.en6 <- lm(log(col_en) ~ log(POP_A) + log(POP_B) + log(distance) + border_DUM + FR_con + EN_con, edges_nz)
summary(lm.en6)
```

### Regional effects

```{r}
# fr with regional dummies
lm.fr.cc1 <- lm(log(col_fr) ~ log(POP_A) + log(POP_B) + log(distance) + CEAST + WEST + NORTH + SOUTH, edges_nz)
summary(lm.fr.cc1)
```

```{r}
# fr with regional dummies
lm.fr.cc2 <- lm(log(col_fr) ~ log(POP_A) + log(POP_B) + log(distance) + CEAST + WEST + NORTH + SOUTH + border_DUM, edges_nz)
summary(lm.fr.cc2)
```

```{r}
# en with regional dummies
lm.en.cc1 <- lm(log(col_en) ~ log(POP_A) + log(POP_B) + log(distance) + CEAST + WEST + NORTH + SOUTH, edges_nz)
summary(lm.en.cc1)
```

```{r}
# with regional dummies and border
lm.en.cc2 <- lm(log(col_en) ~ log(POP_A) + log(POP_B) + log(distance) + CEAST + WEST + NORTH + SOUTH + border_DUM, edges_nz)
summary(lm.en.cc2)
```

## Add predictions

```{r}
# add english residuals (base model with border)
edges_nz$res_en2 <- lm.en2$residuals
edges_nz$res_fr2 <- lm.fr2$residuals
```

```{r}
# calculate as percentage

```


